name: Build release

on:
  push:
    branches:
      - main

jobs:
  checkstyle:
    uses: ./.github/workflows/checkstyle.yml
  unit_test:
    uses: ./.github/workflows/unit_test.yml
  build_release:
    needs: [checkstyle, unit_test]
    name: Building release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Project
        run: |
          make compile
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

