name: Checking Code Style

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v3

      - name: installing python3
        run: sudo apt install -y python3

      - name: checking code style
        run: make checkstyle