name: Creating Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  checkstyle:
    uses: ./.github/workflows/checkstyle.yml

  unit_test:
    uses: ./.github/workflows/unit_test.yml

  run:
    needs: [checkstyle, unit_test]
    name: creating release
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v3

      - name: building project
        run: make compile

      - name: creating release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: uploading release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/GitHubActionsMain
          asset_name: my-executable
          asset_content_type: application/octet-stream

