name: Unit Testing

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v3

      - name: installing requirements
        run: sudo apt install -y build-essential git cmake

      - name: building gtest
        run: make build-gtest

      - name: unit Testing
        run: make test

