name: unit_test

on:
  workflow_call
  push:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt install -y build-essential git cmake

      - name: Build gtest
        run: |
          make build-gtest

      - name: make test
        run: |
          make test

